//
//  HymnsContent.swift
//  Prayer Assistant
//
//  Created by Christopher Fernandes on 19/10/22.
//

import SwiftUI

struct Hymn: Identifiable, Hashable {
    let id = UUID()
    let hymnName: String
    let hymnContent: String
}

struct HymnList {
    static let hymns = [
        Hymn(hymnName: "Amazing Grace", hymnContent: "**Verse 1** \nAmazing Grace how sweet the sound, \nThat saved a wretch like me! \nI once was lost, but now am found; \nWas blind, but now I see. \n\n**Verse 2** \n‘Twas grace that taught my heart to fear, \nAnd grace my fears relieved; \nHow precious did that grace appear \nThe hour I first believed! \n\n**Verse 3** \nThrough many dangers, toils and snares, \nI have already come; \n‘Tis grace hath brought me safe thus far, \nAnd grace will lead me home. \n\n**Verse 4** \nThe Lord has promised good to me, \nHis Word my hope secures; \nHe will my Shield and Portion be, \nAs long as life endures. \n\n**Verse 5** \nYea, when this flesh and heart shall fail, \nAnd mortal life shall cease, \nI shall possess, within the veil, \nA life of joy and peace. \n\n**Verse 6** \nThe earth shall soon dissolve like snow, \nThe sun forbear to shine; \nBut God, Who called me here below, \nWill be forever mine. \n\n**Verse 7** \nWhen we’ve been there ten thousand years, \nBright shining as the sun, \nWe’ve no less days to sing God’s praise \nThan when we’d first begun."),
        
        Hymn(hymnName: "As the Deer", hymnContent: "**Verse 1** \nAs the deer panteth for the water \nSo my soul longeth after Thee \nYou alone are my heart’s desire \nAnd I long to worship Thee \nYou alone are my Strength, my Shield \nTo You alone may my spirit yield \nYou alone are my heart’s desire \nAnd I long to worship Thee. \n\n**Verse 2** \nYou’re my Friend and You are my Brother \nEven though You are a King \nI love You more than any other \nSo much more than anything \nYou alone are my Strength, my Shield \nTo You alone may my spirit yield \nYou alone are my heart’s desire \nAnd I long to worship Thee. \n\n**Verse 3** \nI want You more than gold or silver \nOnly You can satisfy \nYou alone are the real joy-giver \nAnd the apple of my eye \nYou alone are my Strength, my Shield \nTo You alone may my spirit yield \nYou alone are my heart’s desire \nAnd I long to worship Thee."),
        
        Hymn(hymnName: "Blessed Assurance", hymnContent: "**Verse 1** \nBlessèd assurance, Jesus is mine! \nO what a foretaste of glory divine! \nHeir of salvation, purchase of God, \nBorn of His Spirit, washed in His blood. \nThis is my story, this is my song, \nPraising my Savior, all the day long; \nThis is my story, this is my song, \nPraising my Savior, all the day long. \n\n**Verse 2** \nPerfect submission, perfect delight, \nVisions of rapture now burst on my sight; \nAngels descending bring from above \nEchoes of mercy, whispers of love. \nThis is my story, this is my song, \nPraising my Savior, all the day long; \nThis is my story, this is my song, \nPraising my Savior, all the day long. \n\n**Verse 3** \nPerfect submission, all is at rest \nI in my Savior am happy and blest, \nWatching and waiting, looking above, \nFilled with His goodness, lost in His love. \nThis is my story, this is my song, \nPraising my Savior, all the day long; \nThis is my story, this is my song, \nPraising my Savior, all the day long."),
        
        Hymn(hymnName: "Change My Heart", hymnContent: "**Verse 1**\nChange my heart, O God,\nMake it ever true;\nChange my heart, O God,\nMay I be like you.\n\n**Chorus**\nYou are the Potter,\nI am the clay;\nMold me and make me,\nThis is what I pray."),
        
        Hymn(hymnName: "Give Thanks", hymnContent: "**Verse**\nGive thanks with a grateful heart\nGive thanks to the Holy One;\nGive thanks, because He’s given\nJesus Christ, His Son.\n\nGive thanks with a grateful heart\nGive thanks to the Holy One;\nGive thanks, because He’s given\nJesus Christ, His Son.\n\n**Chorus**\nAnd now let the weak say, I am strong,\nLet the poor say, I am rich\nBecause of what the Lord has done for us.\n\nAnd now let the weak say, I am strong,\nLet the poor say, I am rich\nBecause of what the Lord has done for us.\nGive thanks."),
        
        Hymn(hymnName: "How Great Thou Art", hymnContent: "**Verse 1**\nO Lord my God, when I in awesome wonder\nConsider all the works Thy hands have made,\nI see the stars, I hear the rolling thunder,\nThy pow’r thru-out the universe displayed!\n\n**Chorus**\nThen sings my soul, my Savior God, to Thee;\nHow great Thou art, how great Thou art!\nThen sings my soul, my Savior God, to Thee;\nHow great Thou art, how great Thou art!\n\n**Verse 2**\nWhen thru the woods and forest glades I wander\nAnd hear the birds sing sweetly in the trees,\nWhen I look down from lofty mountain grandeur\nAnd hear the brook and feel the gentle breeze,\n\n**Chorus**\nThen sings my soul, my Savior God, to Thee;\nHow great Thou art, how great Thou art!\nThen sings my soul, my Savior God, to Thee;\nHow great Thou art, how great Thou art!\n\n**Verse 3**\nAnd when I think that God, His Son not sparing,\nSent Him to die, I scarce can take it in –\nThat on the cross, my burden gladly bearing,\nHe bled and died to take away my sin!\n\n**Chorus**\nThen sings my soul, my Savior God, to Thee;\nHow great Thou art, how great Thou art!\nThen sings my soul, my Savior God, to Thee;\nHow great Thou art, how great Thou art!\n\n**Verse 4**\nWhen Christ shall come with shout of acclamation\nAnd take me home, what joy shall fill my heart!\nThen I shall bow in humble adoration\nAnd there proclaim, my God, how great Thou art!\n\n**Chorus**\nThen sings my soul, my Savior God, to Thee;\nHow great Thou art, how great Thou art!\nThen sings my soul, my Savior God, to Thee;\nHow great Thou art, how great Thou art!"),
        
        Hymn(hymnName: "I Surrender All", hymnContent: "**Verse 1**\nAll to Jesus, I surrender;\nAll to Him I freely give;\nI will ever love and trust Him,\nIn His presence daily live.\nI surrender all, I surrender all,\nAll to Thee, my blessed Savior,\nI surrender all.\n\n**Verse 2**\nAll to Jesus I surrender;\nHumbly at His feet I bow,\nWorldly pleasures all forsaken;\nTake me, Jesus, take me now.\nI surrender all, I surrender all,\nAll to Thee, my blessed Savior,\nI surrender all.\n\n**Verse 3**\nAll to Jesus, I surrender;\nMake me, Savior, wholly Thine;\nLet me feel the Holy Spirit,\nTruly know that Thou art mine.\nI surrender all, I surrender all,\nAll to Thee, my blessed Savior,\nI surrender all.\n\n**Verse 4**\nAll to Jesus, I surrender;\nLord, I give myself to Thee;\nFill me with Thy love and power;\nLet Thy blessing fall on me.\nI surrender all, I surrender all,\nAll to Thee, my blessed Savior,\nI surrender all."),
        
        Hymn(hymnName: "Shout to The Lord", hymnContent: "**Verse 1**\nMy Jesus, my Savior\nLord there is none like You\nAll of my days, I want to praise\nThe wonders of Your mighty love\nMy Comfort, my Shelter\nTower of Refuge and Strength\nLet every breath, all that I am\nNever cease to worship You\n\n**Chorus**\nShout to the Lord\nAll the earth let us sing\nPower and majesty\nPraise to the King\nMountains bow down\nAnd the sea will roar\nAt the sound of Your Name\n\nI sing for joy\nAt the work of Your hands\nForever I’ll love You,\nforever I’ll stand\nNothing compares to\nThe promise I have in You."),
        
        Hymn(hymnName: "What a Friend", hymnContent: "**Verse 1**\nWhat a Friend we have in Jesus,\nAll our sins and griefs to bear!\nWhat a privilege to carry everything to God in prayer!\nO what peace we often forfeit,\nO what needless pain we bear,\nAll because we do not carry everything to God in prayer.\n\n**Verse 2**\nHave we trials and temptations?\nIs there trouble anywhere?\nWe should never be discouraged; take it to the Lord in prayer.\nCan we find a friend so faithful\nWho will all our sorrows share?\nJesus knows our every weakness; take it to the Lord in prayer.\n\n**Verse 3**\nAre we weak and heavy laden,\nCumbered with a load of care?\nPrecious Savior, still our refuge, take it to the Lord in prayer.\nDo your friends despise, forsake you?\nTake it to the Lord in prayer!\nIn His arms He’ll take and shield you; you will find a solace there."),
        
        
        //        Hymn(hymnName: "Item 1", hymnContent: "Item 1 content"),
        //        Hymn(hymnName: "Item 2", hymnContent: "Item 2 content"),
        //        Hymn(hymnName: "Item 3", hymnContent: "Item 3 content"),
        //        Hymn(hymnName: "Item 4", hymnContent: "Item 4 content"),
    ]
}
